#spring:
#  data:
#    mongodb:
#      host: localhost
#      database: NewEvaluationSystem
#      port: 27017

server:
  port: 8082

jasypt:
  encryptor:
    password: P@dc#%eve!DaDf4n

spring:
  datasource:
    password: ENC(c/3cfPr8qlb69hAhaYYBth26ltfJ/CnfsKX1aGDatafRHESSeIQch2vDaOVWgy3D)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dianping?characterEncoding=utf-8&useSSL=false
      #第一个数据源连接信息
      one:
        url: jdbc:mysql://localhost:3306/game_message?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        password: 123456
      #第二个数据源连接信息
      two:
        url: jdbc:mysql://localhost:3306/game_message_cluster?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        password: 123456